# frozen_string_literal: true

require "test_helper"
require "fileutils"
require "tmpdir"

class ApprovalTest < ActiveSupport::TestCase
  def setup
    RailsXz.reset_config!
    RailsXz::AuditCard.delete_all

    @root = Pathname.new(Dir.mktmpdir)
    FileUtils.mkdir_p(@root.join("app/xz"))
    @root.join("app/xz/order.xz").write("/// @intent Computes the total.\n")

    @card = RailsXz::AuditCard.create!(
      module_name: "order",
      intent: "Computes the payable total.",
      source_path: "app/xz/order.xz",
      declared_effects: ["none"],
      derived_effects: ["none"]
    )

    RailsXz.configure do |config|
      config.git_identity = { name: "alice", email: "alice@example.com" }
    end
  end

  def teardown
    FileUtils.remove_entry(@root) if @root&.exist?
    RailsXz.reset_config!
    RailsXz::AuditCard.delete_all
  end

  def binder
    ->(_header) { "# Generated binding\n" }
  end

  def emitted_header
    <<~HEADER
      /* Generated by `xz build --shared`. Do not edit. */
      #ifndef XZ_LIBXZ_H
      #define XZ_LIBXZ_H

      #include <stdint.h>
      #include <stdbool.h>
      #include <stddef.h>

      typedef struct XzStr { const char* ptr; size_t len; } XzStr;

      double payable_total(double subtotal, double tax_rate);

      #endif /* XZ_LIBXZ_H */
    HEADER
  end

  # Simulates the compiler: a successful `xz build --shared` writes the header
  # beside the library, which is what `bind!` reads.
  def build_runner(fail_on: nil, write_header: true)
    calls = []
    runner = lambda do |argv, env = {}|
      calls << { argv: argv, env: env }
      if argv[0] == "git" && argv[1] == "rev-parse"
        RailsXz::Approval::Outcome.new(stdout: "deadbeef\n", stderr: "", success: true)
      elsif argv[1] == "build" && !(fail_on&.call(argv))
        if write_header
          header = @root.join("vendor/xz/order.h")
          FileUtils.mkdir_p(header.dirname)
          header.write(emitted_header)
        end
        RailsXz::Approval::Outcome.new(stdout: "", stderr: "", success: true)
      elsif fail_on&.call(argv)
        RailsXz::Approval::Outcome.new(stdout: "", stderr: "boom", success: false)
      else
        RailsXz::Approval::Outcome.new(stdout: "", stderr: "", success: true)
      end
    end
    [runner, calls]
  end

  def approve(card = @card, runner:, **options)
    RailsXz::Approval.call(
      card, by: "alice", root: @root, runner: runner, xz_bin: "/fake/xz",
            **{ binder: binder }.merge(options)
    )
  end

  test "builds, binds, and commits, then approves the card" do
    runner, = build_runner

    result = approve(runner: runner)

    assert_equal "approved", @card.reload.status
    assert_equal "alice", @card.decided_by
    assert_equal "deadbeef", @card.commit_sha
    assert_equal "deadbeef", result.commit_sha
    assert_equal @root.join("lib/xz/bindings/order.rb").to_s, result.binding_path
    assert_equal "# Generated binding\n",
                 @root.join("lib/xz/bindings/order.rb").read
  end

  test "runs xz build --shared with the configured output and source" do
    runner, calls = build_runner

    approve(runner: runner)

    build = calls.find { |call| call[:argv][1] == "build" }[:argv]
    assert_equal(
      ["/fake/xz", "build", "--shared", "--out",
       @root.join("vendor/xz/order.so").to_s,
       @root.join("app/xz/order.xz").to_s],
      build
    )
  end

  test "commits the source and binding under the approving identity" do
    runner, calls = build_runner

    approve(runner: runner)

    add = calls.find { |call| call[:argv][1] == "add" }
    assert_equal(
      ["git", "add", "--", "app/xz/order.xz", "lib/xz/bindings/order.rb"],
      add[:argv]
    )
    assert_equal "alice", add[:env]["GIT_AUTHOR_NAME"]
    assert_equal "alice@example.com", add[:env]["GIT_COMMITTER_EMAIL"]

    commit = calls.find { |call| call[:argv][1] == "commit" }
    assert_includes commit[:argv], "xz: Computes the payable total."
  end

  test "derives the commit message from the module name when intent is blank" do
    @card.update!(intent: nil)
    runner, calls = build_runner

    approve(runner: runner)

    commit = calls.find { |call| call[:argv][1] == "commit" }
    assert_includes commit[:argv], "xz: order"
  end

  test "refuses a card that is not pending" do
    @card.approve!(by: "bob")
    runner, = build_runner

    assert_raises(RailsXz::Approval::AlreadyDecided) { approve(runner: runner) }
  end

  test "requires a source_path" do
    @card.update!(source_path: nil)
    runner, = build_runner

    assert_raises(RailsXz::Approval::MissingSource) { approve(runner: runner) }
  end

  test "binds from the compiler header written beside the library" do
    runner, = build_runner
    seen = []
    capturing = ->(header) { seen << header; "# Generated binding\n" }

    approve(runner: runner, binder: capturing)

    assert_equal [@root.join("vendor/xz/order.h").to_s], seen
  end

  test "generates the binding from the emitted header by default" do
    runner, = build_runner

    result = approve(runner: runner, binder: nil)

    generated = @root.join("lib/xz/bindings/order.rb").read
    assert_includes generated, "module Xz::Bindings::Order"
    assert_includes generated, 'xz_library "order.so"'
    assert_includes generated, ":payable_total"
    assert_equal @root.join("vendor/xz/order.h").to_s, result.header_path
    assert_equal "approved", @card.reload.status
  end

  test "requires the compiler header after the build" do
    runner, = build_runner(write_header: false)

    assert_raises(RailsXz::Approval::MissingHeader) { approve(runner: runner) }
    assert_equal "pending", @card.reload.status
  end

  test "leaves the card pending when the build fails" do
    runner, = build_runner(fail_on: ->(argv) { argv[1] == "build" })

    assert_raises(RailsXz::Approval::BuildFailed) { approve(runner: runner) }
    assert_equal "pending", @card.reload.status
  end

  test "reports a missing compiler as a build failure" do
    runner, = build_runner
    original = ENV["XZ_BIN"]
    ENV.delete("XZ_BIN")

    error = assert_raises(RailsXz::Approval::BuildFailed) do
      RailsXz::Approval.call(@card, by: "alice", root: @root, runner: runner,
                                    binder: binder)
    end
    assert_match "XZ_BIN", error.message
  ensure
    ENV["XZ_BIN"] = original
  end

  test "requires a git identity and never falls back to the global one" do
    RailsXz.reset_config!
    runner, = build_runner

    assert_raises(RailsXz::Approval::MissingGitIdentity) { approve(runner: runner) }
    assert_equal "pending", @card.reload.status
  end

  test "leaves the card pending when the commit fails" do
    runner, = build_runner(fail_on: ->(argv) { argv[1] == "commit" })

    assert_raises(RailsXz::Approval::CommitFailed) { approve(runner: runner) }
    assert_equal "pending", @card.reload.status
  end

  test "removes the artifacts it created when the commit fails" do
    runner, = build_runner(fail_on: ->(argv) { argv[1] == "commit" })

    assert_raises(RailsXz::Approval::CommitFailed) { approve(runner: runner) }

    refute @root.join("lib/xz/bindings/order.rb").exist?
    refute @root.join("vendor/xz/order.h").exist?
    assert_equal "pending", @card.reload.status
  end

  test "restores the artifacts it overwrote when the commit fails" do
    binding = @root.join("lib/xz/bindings/order.rb")
    FileUtils.mkdir_p(binding.dirname)
    binding.write("# old binding\n")
    library = @root.join("vendor/xz/order.so")
    FileUtils.mkdir_p(library.dirname)
    library.binwrite("old-library")

    runner, = build_runner(fail_on: ->(argv) { argv[1] == "commit" })

    assert_raises(RailsXz::Approval::CommitFailed) { approve(runner: runner) }

    assert_equal "# old binding\n", binding.read
    assert_equal "old-library", library.binread
  end

  test "unstages the source and binding when the commit fails" do
    runner, calls = build_runner(fail_on: ->(argv) { argv[1] == "commit" })

    assert_raises(RailsXz::Approval::CommitFailed) { approve(runner: runner) }

    reset = calls.find { |call| call[:argv][0] == "git" && call[:argv][1] == "reset" }
    assert_equal(
      ["git", "reset", "--", "app/xz/order.xz", "lib/xz/bindings/order.rb"],
      reset[:argv]
    )
  end

  test "does not touch the index when it never staged anything" do
    RailsXz.reset_config!
    runner, calls = build_runner

    assert_raises(RailsXz::Approval::MissingGitIdentity) { approve(runner: runner) }

    refute calls.any? { |call| call[:argv][0] == "git" && call[:argv][1] == "reset" }
    refute @root.join("lib/xz/bindings/order.rb").exist?
  end

  test "removes a partial build artifact when the build fails" do
    library = @root.join("vendor/xz/order.so")
    runner = lambda do |argv, env = {}|
      if argv[1] == "build"
        FileUtils.mkdir_p(library.dirname)
        library.binwrite("partial")
        RailsXz::Approval::Outcome.new(stdout: "", stderr: "boom", success: false)
      else
        RailsXz::Approval::Outcome.new(stdout: "", stderr: "", success: true)
      end
    end

    assert_raises(RailsXz::Approval::BuildFailed) { approve(runner: runner) }

    refute library.exist?
    assert_equal "pending", @card.reload.status
  end

  test "surfaces a binding generation failure" do
    runner, = build_runner
    failing_binder = ->(_header) { raise RailsXz::Bridge::GenerationError, "bad header" }

    error = assert_raises(RailsXz::Approval::BindFailed) do
      approve(runner: runner, binder: failing_binder)
    end
    assert_match "bad header", error.message
    assert_equal "pending", @card.reload.status
  end
end
