# frozen_string_literal: true

require "test_helper"
require "open3"
require "tmpdir"

class HeaderTest < Minitest::Test
  HEADER = <<~HEADER
    /* Generated by `xz build --shared`. Do not edit. */
    #ifndef XZ_LIBXZ_H
    #define XZ_LIBXZ_H

    #include <stdint.h>
    #include <stdbool.h>
    #include <stddef.h>

    typedef struct XzStr { const char* ptr; size_t len; } XzStr;
    typedef struct XzBytes { const uint8_t* ptr; size_t len; } XzBytes;

    typedef struct Point {
        int64_t x;
        int64_t y;
    } Point;

    Point echo_point(Point p, XzStr label, XzBytes data, void* handle);
    int64_t scale(double value, double* out);

    #endif /* XZ_LIBXZ_H */
  HEADER

  def parse(source)
    RailsXz::Bridge::Header.parse(source, path: "libXz.h")
  end

  def test_parses_function_prototypes
    parsed = parse(HEADER)

    assert_equal %w[echo_point scale], parsed.externs.map(&:name)
  end

  def test_parses_void_parameters_as_empty
    parsed = parse("void noop(void);\n")

    assert_empty parsed.externs[0].params
  end

  def test_void_return_has_no_return_type
    parsed = parse("void noop(void);\n")

    assert_nil parsed.externs[0].return_type
  end

  def test_maps_scalar_types
    parsed = parse("int64_t ok(bool flag, uint64_t size, double ratio, char c);\n")
    params = parsed.externs[0].params

    assert_equal "Int", parsed.externs[0].return_type.name
    assert_equal %w[Bool usize Float Char], params.map { |p| p.type.name }
  end

  def test_maps_str_bytes_and_ptr
    parsed = parse("void take(XzStr s, XzBytes b, void* h);\n")
    params = parsed.externs[0].params

    assert_equal %w[Str Bytes Ptr], params.map { |p| p.type.name }
    refute params.any?(&:mutable)
  end

  def test_maps_pointer_parameters_as_mut
    parsed = parse("int64_t scale(double value, double* out);\n")
    out = parsed.externs[0].params[1]

    assert out.mutable
    assert_equal "Float", out.type.name
    refute parsed.externs[0].params[0].mutable
  end

  def test_maps_double_void_pointer_as_mut_ptr
    parsed = parse("void take(void** slot);\n")
    slot = parsed.externs[0].params[0]

    assert slot.mutable
    assert_equal "Ptr", slot.type.name
  end

  def test_parses_cstruct_records
    parsed = parse(HEADER)
    point = parsed.cstructs.fetch("Point")

    assert_equal %w[x y], point.fields.map(&:name)
    assert_equal %w[Int Int], point.fields.map { |f| f.type.name }
  end

  def test_skips_the_carrier_typedefs
    parsed = parse(HEADER)

    refute parsed.cstructs.key?("XzStr")
    refute parsed.cstructs.key?("XzBytes")
  end

  def test_skips_comments_and_preprocessor_lines
    parsed = parse(<<~HEADER)
      /* block
         comment mentioning extern func ignored() */
      // line comment
      #include <stdint.h>
      #ifndef GUARD
      int64_t noop(void);
      #endif
    HEADER

    assert_equal %w[noop], parsed.externs.map(&:name)
  end

  def test_rejects_an_unknown_c_type
    error = assert_raises(RailsXz::Bridge::HeaderError) do
      parse("int64_t foo(Nope value);\n")
    end

    assert_match(/unknown C type 'Nope'/, error.message)
  end

  def test_rejects_a_pointer_to_value_field
    error = assert_raises(RailsXz::Bridge::HeaderError) do
      parse("typedef struct Bad {\n    int64_t* x;\n} Bad;\n")
    end

    assert_match(/pointer to a value/, error.message)
  end

  def test_rejects_an_unexpected_character
    error = assert_raises(RailsXz::Bridge::HeaderError) do
      parse("@\n")
    end

    assert_match(/unexpected character/, error.message)
  end

  # End-to-end: `xz build --shared` emits a header, the header generates a
  # binding, and the generated binding calls the library. Skipped unless XZ_BIN
  # points at the Xz language CLI.
  def test_generates_from_a_real_header_and_calls_the_library
    skip "XZ_BIN is not set; skipping the header end-to-end" unless RailsXz::Toolchain.configured?

    Dir.mktmpdir("rails-xz-header") do |dir|
      source = File.join(dir, "rich.xz")
      File.write(source, <<~XZ)
        /// @intent  Echoes a point back to the caller.
        /// @effects none
        @export func echo_point(p: Point, label: Str, data: Bytes, handle: Ptr) -> Point
        {
            p
        }

        /// @intent  Scales a value through an out-parameter.
        /// @effects mut
        @export func scale(value: Float, mut out: Float) -> Int
        {
            0
        }

        @cstruct record Point {
            x: Int
            y: Int
        }
      XZ

      lib = File.join(dir, "librich.so")
      build!(lib, source)
      code = RailsXz::Bridge::Generator
             .new(File.join(dir, "librich.h"), lib: lib, module_name: "RichBinding")
             .generate

      namespace = Module.new
      namespace.module_eval(code)
      binding = namespace.const_get(:RichBinding)
      point = binding.const_get(:Point)

      echoed = binding.echo_point(point.new(x: 7, y: 9), "hi", "\x01\x02".b, nil)
      assert_equal point.new(x: 7, y: 9), echoed

      status, out = binding.scale(2.0, 0.0)
      assert_equal 0, status
      assert_equal({ out: 0.0 }, out)
    end
  end

  private

  def build!(lib, source)
    xz = RailsXz::Toolchain.xz_bin
    out, err, status = Open3.capture3(xz, "build", "--shared", "--out", lib, source)

    assert status.success?, "xz build --shared failed: #{err}#{out}"
    assert File.exist?(File.join(File.dirname(lib), "librich.h")),
           "expected the compiler to write the header beside #{lib}"
  end
end
