# frozen_string_literal: true

require "test_helper"
require "tmpdir"

class LoaderTest < Minitest::Test
  HEADER = <<~H
    /* Generated by `xz build --shared`. Do not edit. */
    #ifndef XZ_LIBDEMO_H
    #define XZ_LIBDEMO_H
    typedef struct XzStr { const char* ptr; size_t len; } XzStr;
    double demo_total(double subtotal, double tax_rate);
    #endif
  H

  def test_missing_file_raises_version_error
    loader = RailsXz::Bridge::Loader.new("does/not/exist.so")

    assert_raises(RailsXz::Bridge::VersionError) { loader.load! }
  end

  def test_function_before_load_raises_symbol_error
    loader = RailsXz::Bridge::Loader.new("does/not/exist.so")

    assert_raises(RailsXz::Bridge::SymbolError) do
      loader.function("nope", [], Fiddle::TYPE_VOID)
    end
  end

  def test_ffi_function_before_load_raises_symbol_error
    loader = RailsXz::Bridge::Loader.new("does/not/exist.so")

    assert_raises(RailsXz::Bridge::SymbolError) do
      loader.ffi_function("nope", :void, [])
    end
  end

  def test_matching_abi_digest_verifies
    with_library do |so, header|
      loader = RailsXz::Bridge::Loader.new(
        so, expected_abi_digest: RailsXz::Bridge::Header.digest(header)
      )

      loader.send(:verify_abi_digest!)
    end
  end

  def test_mismatched_abi_digest_raises
    with_library do |so, _header|
      loader = RailsXz::Bridge::Loader.new(so, expected_abi_digest: "sha256:deadbeef")

      error = assert_raises(RailsXz::Bridge::VersionError) { loader.send(:verify_abi_digest!) }
      assert_includes error.message, "does not match the pinned ABI digest"
    end
  end

  def test_missing_companion_header_raises
    Dir.mktmpdir do |dir|
      so = File.join(dir, "libdemo.so")
      File.write(so, "")
      loader = RailsXz::Bridge::Loader.new(so, expected_abi_digest: "sha256:deadbeef")

      error = assert_raises(RailsXz::Bridge::VersionError) { loader.send(:verify_abi_digest!) }
      assert_includes error.message, "companion header"
    end
  end

  def test_no_pin_skips_verification
    Dir.mktmpdir do |dir|
      so = File.join(dir, "libdemo.so")
      File.write(so, "")
      loader = RailsXz::Bridge::Loader.new(so)

      loader.send(:verify_abi_digest!)
    end
  end

  private

  def with_library
    Dir.mktmpdir do |dir|
      so = File.join(dir, "libdemo.so")
      header = File.join(dir, "libdemo.h")
      File.write(so, "")
      File.write(header, HEADER)
      yield so, HEADER
    end
  end
end