# Generated by rails-xz-bridge from app/xz/order.xzint. Do not edit.
require "rails-xz-bridge"

module Xz::Bindings::Order
  extend RailsXz::Bridge::Facade

  xz_library "order.so"

  # extern func payable_total(subtotal: Float, tax_rate: Float) -> Float
  xz_func :payable_total, { subtotal: :float, tax_rate: :float }, :float
end
